// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mock.go -package portfolio_create
//

// Package portfolio_create is a generated GoMock package.
package portfolio_create

import (
	context "context"
	reflect "reflect"

	user_service_client "github.com/yasonofriychuk/tinvest-balancer/internal/service/tinvest/user_service_client"
	gomock "go.uber.org/mock/gomock"
)

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
	isgomock struct{}
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// setToken mocks base method.
func (m *Mockstorage) setToken(cxt context.Context, userId int64, accountId, name string, accountType int64, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "setToken", cxt, userId, accountId, name, accountType, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// setToken indicates an expected call of setToken.
func (mr *MockstorageMockRecorder) setToken(cxt, userId, accountId, name, accountType, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setToken", reflect.TypeOf((*Mockstorage)(nil).setToken), cxt, userId, accountId, name, accountType, token)
}

// Mockcrypter is a mock of crypter interface.
type Mockcrypter struct {
	ctrl     *gomock.Controller
	recorder *MockcrypterMockRecorder
	isgomock struct{}
}

// MockcrypterMockRecorder is the mock recorder for Mockcrypter.
type MockcrypterMockRecorder struct {
	mock *Mockcrypter
}

// NewMockcrypter creates a new mock instance.
func NewMockcrypter(ctrl *gomock.Controller) *Mockcrypter {
	mock := &Mockcrypter{ctrl: ctrl}
	mock.recorder = &MockcrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcrypter) EXPECT() *MockcrypterMockRecorder {
	return m.recorder
}

// Encrypt mocks base method.
func (m *Mockcrypter) Encrypt(text string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", text)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockcrypterMockRecorder) Encrypt(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*Mockcrypter)(nil).Encrypt), text)
}

// MocktInvestService is a mock of tInvestService interface.
type MocktInvestService struct {
	ctrl     *gomock.Controller
	recorder *MocktInvestServiceMockRecorder
	isgomock struct{}
}

// MocktInvestServiceMockRecorder is the mock recorder for MocktInvestService.
type MocktInvestServiceMockRecorder struct {
	mock *MocktInvestService
}

// NewMocktInvestService creates a new mock instance.
func NewMocktInvestService(ctrl *gomock.Controller) *MocktInvestService {
	mock := &MocktInvestService{ctrl: ctrl}
	mock.recorder = &MocktInvestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktInvestService) EXPECT() *MocktInvestServiceMockRecorder {
	return m.recorder
}

// GetAccounts mocks base method.
func (m *MocktInvestService) GetAccounts(ctx context.Context, token string, status user_service_client.AccountStatus) (user_service_client.GetAccountsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccounts", ctx, token, status)
	ret0, _ := ret[0].(user_service_client.GetAccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccounts indicates an expected call of GetAccounts.
func (mr *MocktInvestServiceMockRecorder) GetAccounts(ctx, token, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccounts", reflect.TypeOf((*MocktInvestService)(nil).GetAccounts), ctx, token, status)
}

// MarginIsEnabled mocks base method.
func (m *MocktInvestService) MarginIsEnabled(ctx context.Context, token, accountId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarginIsEnabled", ctx, token, accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarginIsEnabled indicates an expected call of MarginIsEnabled.
func (mr *MocktInvestServiceMockRecorder) MarginIsEnabled(ctx, token, accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarginIsEnabled", reflect.TypeOf((*MocktInvestService)(nil).MarginIsEnabled), ctx, token, accountId)
}
